package flow;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2018-MAY-15  11:58:45 AM
 */
public class mockAccountRetrieval extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2018-MAY-15  11:58:45 AM
	 */
	public mockAccountRetrieval() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2018-MAY-18  08:56:44 AM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = new com.avaya.sce.runtime.Next("mainMenuEval", "Default");
		next.setDebugId(16);
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2018-MAY-18  08:56:44 AM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2018-MAY-18  08:56:44 AM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "getAccountNumber:value", com.avaya.sce.runtime.Expression.STRING_GREATER_THAN, "9", false).setDebugId(74)).evaluate(mySession)) {
			actions = new java.util.ArrayList(4);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:account_number", "999999", true).setDebugId(75));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:balance", "82.18", true).setDebugId(76));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:phone1", "(212) 333-4444", true).setDebugId(77));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:status", "X", true).setDebugId(78));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "getAccountNumber:value", com.avaya.sce.runtime.Expression.STRING_GREATER_THAN, "8", false).setDebugId(109)).evaluate(mySession)) {
			actions = new java.util.ArrayList(4);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:account_number", "888888", true).setDebugId(80));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:balance", "0", true).setDebugId(81));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:phone1", "(212) 333-4444", true).setDebugId(82));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:status", "A", true).setDebugId(83));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "getAccountNumber:value", com.avaya.sce.runtime.Expression.STRING_GREATER_THAN, "7", false).setDebugId(110)).evaluate(mySession)) {
			actions = new java.util.ArrayList(4);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:account_number", "777777", true).setDebugId(85));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:balance", "0", true).setDebugId(86));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:phone1", "", true).setDebugId(87));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:status", "B", true).setDebugId(88));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {
			actions = new java.util.ArrayList(4);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:account_number", "66666", true).setDebugId(112));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:balance", "0", true).setDebugId(113));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:phone1", "(800) 555-1212", true).setDebugId(114));
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("Account:status", "Q", true).setDebugId(115));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
