<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="" descriptorversion="1.0" entrypoint="JavaBusinessRules/Start" forcesubdialogcall="false" frameworkversion="07.20.09.04" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="" submitmethod="get" version="1.0.0" webname="JavaBusinessRules">
    <description/>
    <language name="english" root="en-us"/>
    <dependencies/>
</module>
